
//奥凯页面脚本
$(document).ready(function(){
    $('.tips>div:first-child').click(function(){
    	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.mc_title').show();
    	$('.mc_title>div:first-child').addClass('active');
    	$('.mc_title>div:nth-child(2)').removeClass('active');
    	$('.mc_title>div:nth-child(3)').removeClass('active');
    	$('.flight_message').css('display','block');
    	$('.tgqrule').css('display','none');
    	$('.notice').css('display','none');
    	$('.lvyi_intro').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').addClass('ellipse');
    	$('.page>div>span:nth-child(2)').removeClass('ellipse');
    	$('.page>div>span:nth-child(3)').removeClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});
    });
     $('.tips>div:nth-child(2)').click(function(){
    	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
        $('.mc_title').show();
    	$('.mc_title>div:first-child').removeClass('active');
    	$('.mc_title>div:nth-child(2)').addClass('active');
    	$('.mc_title>div:nth-child(3)').removeClass('active');
    	$('.tgqrule').css('display','block');
    	$('.flight_message').css('display','none');
    	$('.notice').css('display','none');
    	$('.lvyi_intro').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').removeClass('ellipse');
    	$('.page>div>span:nth-child(2)').addClass('ellipse');
    	$('.page>div>span:nth-child(3)').removeClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});
    });
      $('.tips>div:nth-child(3)').click(function(){
    	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.mc_title').show();
        $('.mc_title>div:first-child').removeClass('active');
    	$('.mc_title>div:nth-child(2)').removeClass('active');
    	$('.mc_title>div:nth-child(3)').addClass('active');
    	$('.notice').css('display','block');
    	$('.flight_message').css('display','none');
    	$('.tgqrule').css('display','none');
    	$('.lvyi_intro').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').removeClass('ellipse');
    	$('.page>div>span:nth-child(2)').removeClass('ellipse');
    	$('.page>div>span:nth-child(3)').addClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});

    });
      $('.mc_title>div:first-child').click(function(){
    	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.mc_title').show();
    	$('.mc_title>div:first-child').addClass('active');
    	$('.mc_title>div:nth-child(2)').removeClass('active');
    	$('.mc_title>div:nth-child(3)').removeClass('active');
    	$('.flight_message').css('display','block');
    	$('.tgqrule').css('display','none');
    	$('.notice').css('display','none');
    	$('.lvyi_intro').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').addClass('ellipse');
    	$('.page>div>span:nth-child(2)').removeClass('ellipse');
    	$('.page>div>span:nth-child(3)').removeClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});
    });
     $('.mc_title>div:nth-child(2)').click(function(){
    	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.mc_title').show();
    	$('.mc_title>div:first-child').removeClass('active');
    	$('.mc_title>div:nth-child(2)').addClass('active');
    	$('.mc_title>div:nth-child(3)').removeClass('active');
    	$('.tgqrule').css('display','block');
    	$('.flight_message').css('display','none');
    	$('.notice').css('display','none');
    	$('.lvyi_intro').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').removeClass('ellipse');
    	$('.page>div>span:nth-child(2)').addClass('ellipse');
    	$('.page>div>span:nth-child(3)').removeClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});
    });
      $('.mc_title>div:nth-child(3)').click(function(){
    	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.mc_title').show();
    	$('.mc_title>div:first-child').removeClass('active');
    	$('.mc_title>div:nth-child(2)').removeClass('active');
    	$('.mc_title>div:nth-child(3)').addClass('active');
    	$('.notice').css('display','block');
    	$('.flight_message').css('display','none');
    	$('.tgqrule').css('display','none');
    	$('.lvyi_intro').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').removeClass('ellipse');
    	$('.page>div>span:nth-child(2)').removeClass('ellipse');
    	$('.page>div>span:nth-child(3)').addClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});

    });
     $('.closepage').click(function(){
     	$('.mc_flight_details').css('position','relative');
     	$('.page').css('display','none');
     	$('.mc_flight_details').css('display','none');
     	 $('.app').css('position','');
     	
     });
     $('.btn>span>i').click(function(){
     	if($('.Mongolia').css('display')=='none'){
     		$('.price_detail').css('bottom','55px');
	     	$('.Mongolia').css({'display':'block'});
	     	$('.app').css({'position':'fixed','top':'0px','bottom':'0'});
	     	$(this).addClass('trangletransform');
     	}else{
     		$('.price_detail').css('bottom','-200px');
     	   $('.Mongolia').css('display','none');
     	   $('.app').css('position','');
     	   $(this).removeClass('trangletransform');
     	}
     	
     })
     $('.Mongolia').click(function(){
     	$('.price_detail').css('bottom','-200px');
     	$('.Mongolia').css('display','none');
     	$('.app').css('position','');
     });
     $('.delete').click(function(){
     	$('.tel>input').val('');
     });
     $('.addperson').click(function(){
     	window.open('https://www.baidu.com/');
     })
     $('.bugtips').click(function(){
     	$('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
        $('.mc_title').show();
        $('.mc_title>div:first-child').removeClass('active');
    	$('.mc_title>div:nth-child(2)').removeClass('active');
    	$('.mc_title>div:nth-child(3)').addClass('active');
    	$('.notice').css('display','block');
    	$('.flight_message').css('display','none');
    	$('.tgqrule').css('display','none');
    	$('.page>div>span').show();
    	$('.page>div>span:first-child').removeClass('ellipse');
    	$('.page>div>span:nth-child(2)').removeClass('ellipse');
    	$('.page>div>span:nth-child(3)').addClass('ellipse');
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});
     })
     for(var i=0 ;i<$('.passenger_details').length;i++){
            $('.passenger_details').eq(i).attr('data-i',i);
     	}
     $('.passenger_details>i').click(function(){
     	$('.passenger_details').eq(parseInt($(this).parent().attr('data-i'))).remove();
     	for(var i=0 ;i<$('.passenger_details').length;i++){
            $('.passenger_details').eq(i).attr('data-i',i);
     	}
     });
     $('.lvyi>em').click(function(){
        $('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.lvyi_intro').css('display','block');
    	$('.mc_title').hide();
    	$('.notice').css('display','none');
    	$('.flight_message').css('display','none');
    	$('.tgqrule').css('display','none');
    	$('.page>div>span').hide();
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});
     });
     $('.readfirst>div>span').click(function(){
     	  $('.mc_flight_details').css('position','fixed');
    	$('.mc_flight_details').css('display','block');
    	$('.lvyi_intro').css('display','block');
    	$('.mc_title').hide();
    	$('.notice').css('display','none');
    	$('.flight_message').css('display','none');
    	$('.tgqrule').css('display','none');
    	$('.page>div>span').hide();
    	$('.page').css('display','block');
    	$('.app').css({'position':'fixed','top':'0px'});

     });
     $('.check').click(function(){
     	$(this).toggleClass('uncheck');
     });
     $('.pay').click(function(){
     	alert('去支付');
     })


})